import * as vscode from 'vscode';

export interface AIComment {
    file: string;
    line: number;
    content: string;
    matchedPattern: string;
    severity: 'warning' | 'info';
}

export class AICommentDetector {
    /** Built-in patterns that identify AI/Copilot-generated comments */
    private readonly BUILTIN_PATTERNS: Array<{ regex: RegExp; label: string }> = [
        // Explicit Copilot references
        { regex: /github\s+copilot/i,                  label: 'GitHub Copilot reference' },
        { regex: /generated\s+by\s+(github\s+)?copilot/i, label: 'Copilot-generated marker' },
        { regex: /copilot\s+(suggestion|assisted|generated|wrote|added)/i, label: 'Copilot action marker' },
        { regex: /@copilot/i,                           label: '@copilot tag' },
        { regex: /\[copilot\]/i,                        label: '[Copilot] tag' },

        // Generic AI references
        { regex: /ai[-\s]?generated/i,                 label: 'AI-generated marker' },
        { regex: /generated\s+by\s+ai/i,               label: 'Generated by AI' },
        { regex: /suggested\s+by\s+(ai|copilot|llm)/i, label: 'Suggested by AI' },
        { regex: /\[ai\]/i,                             label: '[AI] tag' },
        { regex: /\[generated\]/i,                      label: '[generated] tag' },
        { regex: /\[auto[-\s]?generated\]/i,            label: '[auto-generated] tag' },

        // Other AI tools
        { regex: /chatgpt/i,           label: 'ChatGPT reference' },
        { regex: /claude\s+(ai|generated|suggestion)/i, label: 'Claude AI reference' },
        { regex: /openai\s+generated/i, label: 'OpenAI generated' },
        { regex: /llm\s+generated/i,   label: 'LLM generated' },
        { regex: /tabnine/i,           label: 'Tabnine reference' },
        { regex: /codeium/i,           label: 'Codeium reference' },

        // Suspicious auto-generated patterns in comment blocks
        { regex: /\/\/\s*auto[-\s]?generated\s+(by|code|comment)/i, label: 'Auto-generated comment' },
        { regex: /#\s*auto[-\s]?generated\s+(by|code|comment)/i,    label: 'Auto-generated comment' },
        { regex: /todo:\s*.*(copilot|ai tool|generated)/i,          label: 'AI-related TODO' },
        { regex: /fixme:\s*.*(copilot|ai tool|generated)/i,         label: 'AI-related FIXME' },
    ];

    private getCustomPatterns(): Array<{ regex: RegExp; label: string }> {
        const cfg = vscode.workspace.getConfiguration('precommitGuardian');
        const patterns = cfg.get<string[]>('aiCommentPatterns', []);
        return patterns.flatMap(p => {
            try {
                return [{ regex: new RegExp(p, 'i'), label: `Custom: ${p}` }];
            } catch {
                return [];
            }
        });
    }

    detectInDiff(diff: string): AIComment[] {
        const allPatterns = [...this.BUILTIN_PATTERNS, ...this.getCustomPatterns()];
        const comments: AIComment[] = [];

        let currentFile = '';
        let currentLine = 0;
        const lines = diff.split('\n');

        for (const rawLine of lines) {
            // File header
            if (rawLine.startsWith('diff --git ')) {
                const m = rawLine.match(/diff --git a\/.+ b\/(.+)/);
                if (m) { currentFile = m[1]; currentLine = 0; }
                continue;
            }
            // Hunk header — reset line counter
            if (rawLine.startsWith('@@')) {
                const m = rawLine.match(/@@ -\d+(?:,\d+)? \+(\d+)/);
                if (m) currentLine = parseInt(m[1]) - 1;
                continue;
            }

            if (rawLine.startsWith('+') && !rawLine.startsWith('+++')) {
                currentLine++;
                const codeLine = rawLine.substring(1);
                const isCommentLike = /^\s*(\/\/|\/\*|\*|#|<!--|\{\/\*|--|\*\/)/.test(codeLine)
                    || /\/\//.test(codeLine)
                    || /#/.test(codeLine);

                if (isCommentLike) {
                    for (const { regex, label } of allPatterns) {
                        if (regex.test(codeLine)) {
                            comments.push({
                                file: currentFile,
                                line: currentLine,
                                content: codeLine.trim(),
                                matchedPattern: label,
                                severity: 'warning'
                            });
                            break; // one match per line is enough
                        }
                    }
                }
            } else if (!rawLine.startsWith('-') && !rawLine.startsWith('\\')) {
                currentLine++;
            }
        }

        return comments;
    }

    /** Markdown report for chat output */
    formatReport(comments: AIComment[]): string {
        if (comments.length === 0) {
            return '✅ **No AI-generated comments detected** in local changes.\n';
        }

        const byFile = comments.reduce<Record<string, AIComment[]>>((acc, c) => {
            (acc[c.file] ??= []).push(c);
            return acc;
        }, {});

        let md = `⚠️ **${comments.length} AI-generated comment(s) found** — these should be removed or replaced:\n\n`;
        for (const [file, items] of Object.entries(byFile)) {
            md += `**📄 \`${file}\`**\n`;
            for (const item of items) {
                const preview = item.content.length > 90
                    ? item.content.substring(0, 87) + '...'
                    : item.content;
                md += `  - Line **${item.line}** *(${item.matchedPattern})*: \`${preview}\`\n`;
            }
            md += '\n';
        }
        md += '> 💡 Replace AI-generated comments with accurate, context-specific documentation that reflects the actual implementation.\n';
        return md;
    }
}