export class CodeAnalyzer {
    /** Full review prompt: AI comments + optimization + deep analysis + security */
    buildFullReviewPrompt(diff: string, files: string[], branch: string): string {
        return `You are a senior software engineer performing a **pre-commit code review**.
Your goal is to ensure the commit is as clean, correct, and maintainable as possible.

**Branch:** \`${branch}\`
**Files changed (${files.length}):**
${files.map(f => `  - ${f}`).join('\n')}

---

## Review Checklist

### 🤖 1. AI-Generated Content
- Placeholder or templated comments (e.g., "This function does X")
- Generic docstrings not specific to the implementation
- Inline TODO/FIXME referencing AI tools
- Boilerplate code that wasn't adapted to context

### ⚡ 2. Code Optimization
- Inefficient loops, unnecessary iterations, or O(n²) patterns where O(n) is possible
- Redundant variables, duplicate logic, or dead code
- Unnecessary re-renders (React) or expensive recomputations
- Missing memoization or caching opportunities
- Synchronous operations that should be async

### 🔍 3. Deep Code Analysis
- Unhandled null/undefined (optional chaining missing)
- Missing try/catch for async operations or I/O
- Race conditions or unresolved promise chains
- Memory leaks (event listeners, subscriptions not cleaned up)
- Type safety issues (TypeScript any, unsafe casts)
- Edge cases not covered (empty arrays, zero values, negative numbers)

### 🔐 4. Security
- Hardcoded credentials, tokens, or API keys
- SQL/command injection risks
- Missing input validation or sanitization
- Exposed sensitive data in logs or error messages
- Insecure direct object references

### 🏗️ 5. Maintainability
- Functions doing more than one thing (SRP violation)
- Functions longer than 40 lines without clear justification
- Magic numbers/strings (should be named constants)
- Poor or misleading variable/function names
- Complex conditionals that need extraction
- Missing or incorrect error messages

### ✅ 6. Quick Blockers
- \`console.log\`, \`print\`, \`debugger\` statements left in production code
- Commented-out code blocks
- Incomplete implementations (throws NotImplementedException, empty catch blocks)
- Unused imports

---

## Git Diff:
\`\`\`diff
${diff}
\`\`\`

---

## Response Format:

### 📊 Executive Summary
(2–3 sentences on overall quality and commit readiness)

### Issues Found
(Group by category. Skip categories with no issues. For each issue include:)
- **File + Line/Area**: ...
- **Severity**: 🔴 Critical | 🟡 Warning | 🔵 Info
- **Issue**: ...
- **Fix**: ...

### ✅ Commit Readiness Score: X/10
(Brief justification)

Be specific. Reference actual code from the diff. If a category is clean, write a single "✅ Looks good" line for it.`;
    }

    /** Focused quick-check prompt for the /check command */
    buildQuickCheckPrompt(diff: string, files: string[]): string {
        return `Perform a **quick commit-readiness check** on this diff.

Files: ${files.join(', ')}

Check ONLY for these blockers (respond with ✅ or ❌ for each):

1. **Debug statements**: \`console.log\`, \`print()\`, \`debugger\`, \`pp\`, \`logger.debug\` left in production code
2. **Commented-out code blocks**: Large sections of commented code (not documentation)
3. **Hardcoded secrets**: passwords, tokens, API keys, private keys in code
4. **Incomplete code**: empty catch blocks, \`throw new Error('TODO')\`, \`pass\` in critical paths
5. **TODO/FIXME added**: new TODOs or FIXMEs introduced in this diff
6. **Unused imports**: obvious unused imports in changed files
7. **AI comment markers**: "generated by copilot", "AI-generated", etc.

Diff:
\`\`\`diff
${diff}
\`\`\`

**Format your response as:**
\`\`\`
✅/❌ Debug statements: [details if ❌]
✅/❌ Commented-out code: [details if ❌]
✅/❌ Hardcoded secrets: [details if ❌]
✅/❌ Incomplete code: [details if ❌]
✅/❌ TODO/FIXME added: [details if ❌]
✅/❌ Unused imports: [details if ❌]
✅/❌ AI comment markers: [details if ❌]

VERDICT: ✅ READY TO COMMIT | ❌ NEEDS FIXES BEFORE COMMIT
\`\`\``;
    }
}